worlds:
  - name: world
    nick: "主世界"
    locations:
      - name: example1_1
        nick: "主城"
        position: [0, 64, 0 , 0, 0]
      - name: example1_2
        nick: "末地门"
        position: [100, 64, 100 , 0, 0]
  - name: world_nether
    nick: "下界"
    locations:
      - name: example2_1
        position: [0, 64, 0 , 0, 0]
servers:
  - server: lobby
    prefix: "§e[大厅] "
yggdrasil-api: https://littleskin.cn/api/yggdrasil